version: '3.8'

services:
 
  # ================= DATA BASES =================
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - empresa-aerea-net

  # =============== MICROSERVIÇOS ===============

  ms-auth:
    build:
      context: ./backend/ms-auth
      dockerfile: Dockerfile
    container_name: ms-auth
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo-db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: auth_db
    depends_on:
      - mongo-db
    networks:
      - empresa-aerea-net

  ms-cliente:
    build:
      context: ./backend/ms-cliente
      dockerfile: Dockerfile
    container_name: ms-cliente
    ports:
      - "8081:8081"
    networks:
      - empresa-aerea-net

  ms-funcionario:
    build:
      context: ./backend/ms-funcionario
      dockerfile: Dockerfile
    container_name: ms-funcionario
    ports:
      - "8082:8082"
    networks:
      - empresa-aerea-net

  ms-reserva:
    build:
      context: ./backend/ms-reservas
      dockerfile: Dockerfile
    container_name: ms-reserva
    ports:
      - "8083:8083"
    networks:
      - empresa-aerea-net

  ms-voos:
    build:
      context: ./backend/ms-voos
      dockerfile: Dockerfile
    container_name: ms-voos
    ports:
      - "8084:8084"
    networks:
      - empresa-aerea-net

  # =============== API GATEWAY ===============
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - ms-auth
      - ms-cliente
      - ms-funcionario
      - ms-reserva
      - ms-voos
    environment:
      PORT: 3000
      MS_AUTH_URL: http://ms-auth:8080
      MS_CLIENTE_URL: http://ms-cliente:8081
      MS_FUNCIONARIO_URL: http://ms-funcionario:8082
      MS_RESERVA_URL: http://ms-reserva:8083
      MS_VOOS_URL: http://ms-voos:8084
    networks:
      - empresa-aerea-net

  # =============== NETWORK ===============
networks:
  empresa-aerea-net:
    driver: bridge