--CREATE DATABASE cliente_db;
--CREATE DATABASE funcionario_db;
--CREATE DATABASE reserva_db;
--CREATE DATABASE voos_db;
--CREATE DATABASE saga_db;

CREATE DATABASE IF NOT EXISTS cliente_db;
CREATE DATABASE IF NOT EXISTS funcionario_db;
CREATE DATABASE IF NOT EXISTS reserva_db;
CREATE DATABASE IF NOT EXISTS voos_db;
CREATE DATABASE IF NOT EXISTS saga_db;