spring.application.name=ms-auth
api.security.token.secret=secret

#================================================= MongoDB Config
spring.data.mongodb.host=mongo-db
spring.data.mongodb.port=27017
spring.data.mongodb.database=auth_db
spring.data.mongodb.username=admin
spring.data.mongodb.password=admin